import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { QuoteRequest } from '@/types';
import { supabase } from '@/lib/Client';

// Extender el tipo jsPDF para incluir autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: typeof autoTable;
    lastAutoTable: {
      finalY: number;
    };
  }
}

// Servicio para generar PDFs de reportes AI
export class PDFService {
  private static instance: PDFService;

  private constructor() {}

  public static getInstance(): PDFService {
    if (!PDFService.instance) {
      PDFService.instance = new PDFService();
    }
    return PDFService.instance;
  }

  /**
   * Genera un PDF del reporte AI en el idioma especificado
   */
  generateReportPDF(
    quoteRequest: QuoteRequest,
    language: 'es' | 'en' = 'es'
  ): jsPDF {
    const isSpanish = language === 'es';
    const report = quoteRequest.aiReport;

    if (!report) {
      throw new Error(isSpanish ? 'No hay reporte AI disponible' : 'No AI report available');
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    let yPos = 20;

    // Colores
    const primaryColor:   [number, number, number] = [99, 102, 241];  // Indigo
    const secondaryColor: [number, number, number] = [139, 92, 246];  // Purple
    const textColor:      [number, number, number] = [31, 41, 55];
    const lightGray:      [number, number, number] = [243, 244, 246];

    // Logo y título
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, pageWidth, 50, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(
      isSpanish ? 'INFORME DE COTIZACIÓN' : 'QUOTE REPORT',
      pageWidth / 2,
      25,
      { align: 'center' }
    );

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(
      isSpanish ? 'Generado por QuoteAI' : 'Generated by QuoteAI',
      pageWidth / 2,
      35,
      { align: 'center' }
    );

    doc.setFontSize(10);
    doc.text(
      new Date().toLocaleDateString(language === 'es' ? 'es-ES' : 'en-US'),
      pageWidth / 2,
      42,
      { align: 'center' }
    );

    yPos = 65;

    // Información del cliente
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(isSpanish ? 'INFORMACIÓN DEL CLIENTE' : 'CLIENT INFORMATION', margin, yPos);

    yPos += 10;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');

    const clientInfo = [
      [isSpanish ? 'Nombre:' : 'Name:', quoteRequest.fullName],
      [isSpanish ? 'Email:' : 'Email:', quoteRequest.email],
      [isSpanish ? 'Teléfono:' : 'Phone:', quoteRequest.phone],
      [isSpanish ? 'Empresa:' : 'Company:', quoteRequest.company || (isSpanish ? 'N/A' : 'N/A')],
      [isSpanish ? 'Servicio:' : 'Service:', quoteRequest.service],
    ];

    // Usar autoTable correctamente con el nuevo import
    autoTable(doc, {
      startY: yPos,
      margin: { left: margin, right: margin },
      body: clientInfo,
      theme: 'plain',
      styles: {
        fontSize: 11,
        cellPadding: 3,
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 40 },
        1: { cellWidth: 'auto' },
      },
    });

    yPos = doc.lastAutoTable.finalY + 15;

    // Resumen del proyecto
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(isSpanish ? 'RESUMEN DEL PROYECTO' : 'PROJECT SUMMARY', margin, yPos);

    yPos += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    // Dividir texto largo en líneas
    const splitDetails = doc.splitTextToSize(quoteRequest.projectDetails, pageWidth - margin * 2);
    doc.text(splitDetails, margin, yPos);

    yPos += splitDetails.length * 5 + 15;

    // Informe AI
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(margin, yPos - 8, pageWidth - margin * 2, 12, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(
      isSpanish ? 'ANÁLISIS DE LA IA' : 'AI ANALYSIS',
      pageWidth / 2,
      yPos,
      { align: 'center' }
    );

    yPos += 15;
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);

    // Tabla de información clave
    const keyInfo = [
      [
        isSpanish ? 'Tiempo Estimado' : 'Estimated Time',
        report.estimatedTime,
        isSpanish ? 'Nivel de Dificultad' : 'Difficulty Level',
        this.translateDifficulty(report.difficultyLevel, language),
      ],
      [
        isSpanish ? 'Costo Total' : 'Total Cost',
        `$${report.totalCost.toLocaleString()}`,
        isSpanish ? 'Miembros del Equipo' : 'Team Members',
        `${report.requiredTeamMembers} ${isSpanish ? 'personas' : 'people'}`,
      ],
    ];

    autoTable(doc, {
      startY: yPos,
      margin: { left: margin, right: margin },
      body: keyInfo,
      theme: 'grid',
      styles: {
        fontSize: 10,
        cellPadding: 8,
        valign: 'middle',
      },
      headStyles: {
        fillColor: secondaryColor,
        textColor: 255,
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { fontStyle: 'bold', fillColor: lightGray },
        2: { fontStyle: 'bold', fillColor: lightGray },
      },
    });

    yPos = doc.lastAutoTable.finalY + 15;

    // Desglose de costos
    if (yPos > 200) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(isSpanish ? 'DESGLOSE DE COSTOS' : 'COST BREAKDOWN', margin, yPos);

    yPos += 10;

    const costData = [
      [isSpanish ? 'Desarrollo' : 'Development', `$${report.partialCosts.development.toLocaleString()}`],
      [isSpanish ? 'Diseño' : 'Design', `$${report.partialCosts.design.toLocaleString()}`],
      [isSpanish ? 'Pruebas' : 'Testing', `$${report.partialCosts.testing.toLocaleString()}`],
      [isSpanish ? 'Despliegue' : 'Deployment', `$${report.partialCosts.deployment.toLocaleString()}`],
    ];

    if (report.partialCosts.projectManagement) {
      costData.push([
        isSpanish ? 'Gestión de Proyecto' : 'Project Management',
        `$${report.partialCosts.projectManagement.toLocaleString()}`,
      ]);
    }

    if (report.partialCosts.maintenance) {
      costData.push([
        isSpanish ? 'Mantenimiento Mensual' : 'Monthly Maintenance',
        `$${report.partialCosts.maintenance.toLocaleString()}`,
      ]);
    }

    costData.push([
      isSpanish ? 'COSTO TOTAL' : 'TOTAL COST',
      `$${report.totalCost.toLocaleString()}`,
    ]);

    autoTable(doc, {
      startY: yPos,
      margin: { left: margin, right: margin },
      body: costData,
      theme: 'grid',
      styles: {
        fontSize: 11,
        cellPadding: 8,
      },
      columnStyles: {
        0: { fontStyle: 'bold' },
        1: { halign: 'right' },
      },
      didParseCell: function (data: any) {
        if (data.row.index === costData.length - 1) {
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.fillColor = primaryColor;
          data.cell.styles.textColor = 255;
        }
      },
    });

    yPos = doc.lastAutoTable.finalY + 15;

    // Tecnologías recomendadas
    if (yPos > 200) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(
      isSpanish ? 'TECNOLOGÍAS RECOMENDADAS' : 'RECOMMENDED TECHNOLOGIES',
      margin,
      yPos
    );

    yPos += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const techText = report.recommendedTechnologies.join(', ');
    const splitTech = doc.splitTextToSize(techText, pageWidth - margin * 2);
    doc.text(splitTech, margin, yPos);

    yPos += splitTech.length * 5 + 15;

    // Recomendaciones
    if (report.recommendations && report.recommendations.length > 0) {
      if (yPos > 180) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(isSpanish ? 'RECOMENDACIONES' : 'RECOMMENDATIONS', margin, yPos);

      yPos += 10;
      doc.setFontSize(10);

      report.recommendations.forEach((rec, index) => {
        if (yPos > 260) {
          doc.addPage();
          yPos = 20;
        }
        const splitRec = doc.splitTextToSize(`${index + 1}. ${rec}`, pageWidth - margin * 2 - 10);
        doc.text(splitRec, margin + 5, yPos);
        yPos += splitRec.length * 5 + 5;
      });
    }

    // Hitos del proyecto
    if (report.milestones && report.milestones.length > 0) {
      if (yPos > 180) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(isSpanish ? 'HITOS DEL PROYECTO' : 'PROJECT MILESTONES', margin, yPos);

      yPos += 10;
      doc.setFontSize(10);

      report.milestones.forEach((milestone, index) => {
        if (yPos > 260) {
          doc.addPage();
          yPos = 20;
        }
        const splitMilestone = doc.splitTextToSize(
          `${index + 1}. ${milestone}`,
          pageWidth - margin * 2 - 10
        );
        doc.text(splitMilestone, margin + 5, yPos);
        yPos += splitMilestone.length * 5 + 5;
      });
    }

    // Notas adicionales
    if (report.additionalNotes) {
      if (yPos > 220) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(isSpanish ? 'NOTAS ADICIONALES' : 'ADDITIONAL NOTES', margin, yPos);

      yPos += 10;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');

      const splitNotes = doc.splitTextToSize(report.additionalNotes, pageWidth - margin * 2);
      doc.text(splitNotes, margin, yPos);
    }

    // Pie de página
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFillColor(lightGray[0], lightGray[1], lightGray[2]);
      doc.rect(0, doc.internal.pageSize.height - 20, pageWidth, 20, 'F');

      doc.setTextColor(100, 100, 100);
      doc.setFontSize(9);
      doc.text(
        isSpanish
          ? `QuoteAI - Página ${i} de ${pageCount}`
          : `QuoteAI - Page ${i} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.height - 8,
        { align: 'center' }
      );
    }

    return doc;
  }

  /**
   * Descarga el PDF del reporte
   */
  downloadReportPDF(
    quoteRequest: QuoteRequest,
    language: 'es' | 'en' = 'es'
  ): void {
    const doc = this.generateReportPDF(quoteRequest, language);
    const fileName = `quote-report-${quoteRequest.fullName.replace(/\s+/g, '-').toLowerCase()}-${language}.pdf`;
    doc.save(fileName);
  }

  /**
   * Obtiene el PDF como blob para previsualización
   */
  getReportPDFBlob(
    quoteRequest: QuoteRequest,
    language: 'es' | 'en' = 'es'
  ): Blob {
    const doc = this.generateReportPDF(quoteRequest, language);
    return doc.output('blob');
  }

  /**
   * Sube el PDF a Supabase Storage y devuelve la URL pública
   */
  async uploadPDFToStorage(
    quoteRequest: QuoteRequest,
    language: 'es' | 'en' = 'es'
  ): Promise<string> {
    try {
      const pdfBlob = this.getReportPDFBlob(quoteRequest, language);
      const fileName = `quote-report-${quoteRequest.id}-${language}-${Date.now()}.pdf`;
      const filePath = `reports/${fileName}`;

      console.log('Subiendo PDF a Supabase Storage:', {
        bucket: 'reports',
        path: filePath,
        size: pdfBlob.size,
      });

      // Subir el archivo a Supabase Storage
      const { error: uploadError } = await supabase.storage
        .from('reports')
        .upload(filePath, pdfBlob, {
          cacheControl: '3600',
          upsert: false,
          contentType: 'application/pdf',
        });

      if (uploadError) {
        console.error('Error subiendo PDF:', uploadError);
        throw new Error(`Error al subir PDF: ${uploadError.message}`);
      }

      // Obtener la URL pública
      const { data: publicUrlData } = supabase.storage
        .from('reports')
        .getPublicUrl(filePath);

      console.log('PDF subido exitosamente:', publicUrlData.publicUrl);
      return publicUrlData.publicUrl;
    } catch (error) {
      console.error('Error en uploadPDFToStorage:', error);
      throw error;
    }
  }

  /**
   * Elimina un PDF del storage de Supabase
   */
  async deletePDFFromStorage(pdfUrl: string): Promise<void> {
    try {
      const urlObj = new URL(pdfUrl);
      const pathParts = urlObj.pathname.split('/');
      const filePath = pathParts.slice(pathParts.indexOf('reports') + 1).join('/');

      console.log('Eliminando PDF de Supabase Storage:', filePath);

      const { error } = await supabase.storage
        .from('reports')
        .remove([filePath]);

      if (error) {
        console.error('Error eliminando PDF:', error);
        throw error;
      }

      console.log('PDF eliminado exitosamente');
    } catch (error) {
      console.error('Error en deletePDFFromStorage:', error);
      throw error;
    }
  }

  /**
   * Lista todos los PDFs de un quote request
   */
  async listPDFsForQuoteRequest(quoteRequestId: string): Promise<string[]> {
    try {
      const { data, error } = await supabase.storage
        .from('reports')
        .list('reports', {
          search: `quote-report-${quoteRequestId}`,
        });

      if (error) {
        console.error('Error listando PDFs:', error);
        throw error;
      }

      return (data || []).map((file) => {
        const { data: publicUrlData } = supabase.storage
          .from('reports')
          .getPublicUrl(`reports/${file.name}`);
        return publicUrlData.publicUrl;
      });
    } catch (error) {
      console.error('Error en listPDFsForQuoteRequest:', error);
      throw error;
    }
  }

  /**
   * Traduce el nivel de dificultad
   */
  private translateDifficulty(
    difficulty: string,
    language: 'es' | 'en'
  ): string {
    if (language === 'en') return difficulty;

    const translations: Record<string, string> = {
      low: 'Baja',
      medium: 'Media',
      high: 'Alta',
    };

    return translations[difficulty] || difficulty;
  }
}

// Exportar instancia singleton
export const pdfService = PDFService.getInstance();

// Funciones helper
export function downloadAIReportPDF(
  quoteRequest: QuoteRequest,
  language: 'es' | 'en' = 'es'
): void {
  pdfService.downloadReportPDF(quoteRequest, language);
}

export function getAIReportPDFBlob(
  quoteRequest: QuoteRequest,
  language: 'es' | 'en' = 'es'
): Blob {
  return pdfService.getReportPDFBlob(quoteRequest, language);
}

export async function uploadAIReportPDF(
  quoteRequest: QuoteRequest,
  language: 'es' | 'en' = 'es'
): Promise<string> {
  return pdfService.uploadPDFToStorage(quoteRequest, language);
}

export async function deleteAIReportPDF(pdfUrl: string): Promise<void> {
  return pdfService.deletePDFFromStorage(pdfUrl);
}

export async function listAIReportPDFs(quoteRequestId: string): Promise<string[]> {
  return pdfService.listPDFsForQuoteRequest(quoteRequestId);
}